### PR TITLE
Update to f-m-p 3.1.1

### PR DESCRIPTION
**Pull request by rhuss**

### CODE REVIEW

**Comment by rhuss** [comment]
[merge]

**Comment by rawlingsj** [comment]
add to whitelist

**Comment by rhuss** [comment]
[merge]

thanks for the karma, @rawlingsj ;-) !

**Comment by rawlingsj** [comment]
@rhuss dam - looks like you need to be listed in the CI server, one sec..

**Comment by rawlingsj** [comment]
retest this please

**Comment by rhuss** [comment]
[merge]

**Comment by rawlingsj** [comment]
yay!

**Comment by rhuss** [comment]
yeah, thanks @rawlingsj  ;-) happy evening ;-)

**Pull request merged**
